# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "now_and_later"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jordan Glasner"]
  s.date = "2012-10-26"
  s.description = "app/services"
  s.email = "jordan@digitalignition.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/now_and_later.rb",
    "lib/now_and_later/engine.rb",
    "lib/now_and_later/enqueue.rb",
    "lib/now_and_later/enqueue/with_delayed_job.rb",
    "lib/now_and_later/enqueue/with_resque.rb",
    "lib/now_and_later/queue.rb",
    "lib/now_and_later/runner.rb",
    "lib/now_and_later/service.rb",
    "lib/now_and_later/service/with_resque.rb",
    "spec/now_and_later/engine_spec.rb",
    "spec/now_and_later/enqueue_service_spec.rb",
    "spec/now_and_later/queue/with_delayed_job_spec.rb",
    "spec/now_and_later/queue_spec.rb",
    "spec/now_and_later/service_spec.rb",
    "spec/now_and_later_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/glasner/now_and_later"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "new app/services can be ran now or later"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

